### ISSUE TITLE
Error by Start analysis with 6 gate and 6 flows - Hostename is missing

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTAnalytics#205]
- all bounding boxes of the trajectories have the same timestamp (most likely not the reason)
- 6 gates
- 6 flows
- saving of the events give a empty eventlist

cmd error output: `Start analysis
Exception in Tkinter callback
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\application\analysis.py", line 49, in _run_on_single_track
    _events = section_action_detector._detect(section=_section, track=track)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\application\eventlist.py", line 68, in _detect
    events: list[Event] = self.intersector.intersect(
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\domain\intersect.py", line 350, in intersect
    events.append(event_builder.create_event(next_detection))
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\domain\event.py", line 265, in create_event
    hostname=self.extract_hostname(detection.input_file_path),
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\domain\event.py", line 179, in extract_hostname
    raise InproperFormattedFilename(
OTAnalytics.domain.event.InproperFormattedFilename: Could not parse . Hostname is missing.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\venv\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\plugin_ui\customtkinter_gui\frame_analysis.py", line 41, in _start_analysis
    self._viewmodel.start_analysis()
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\plugin_ui\customtkinter_gui\dummy_viewmodel.py", line 481, in start_analysis
    self._application.start_analysis()
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\application\application.py", line 171, in start_analysis
    events = self._intersect.run(tracks, sections)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\application\analysis.py", line 30, in run
    return self._intersect_parallelizer.execute(
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\plugin_intersect_parallelization\multiprocessing.py", line 22, in execute
    events = pool.starmap(
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 774, in get
    raise self._value
OTAnalytics.domain.event.InproperFormattedFilename: Could not parse . Hostname is missing.`

**Comment by arminkollascheck** [comment]
Happens if you have a false path at the single detections.
