### ISSUE TITLE
Error by "Add to Movement", does this button has a function?

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTAnalytics#81]
- added some gates/sections
- delated some sections
- marked every section
- pressed Add to Movement
- Error

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\gui.py", line 89, in <lambda>
    self.frame_sections.add_section_to_movement(
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\helpers\view_sections.py", line 216, in add_section_to_movement
    detector_name = self.tree_sections.item(item, "text")
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python39\lib\tkinter\ttk.py", line 1378, in item
    return _val_or_dict(self.tk, kw, self._w, "item", item)
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python39\lib\tkinter\ttk.py", line 298, in _val_or_dict
    res = tk.call(*(args + options))
_tkinter.TclError: Item I003 I004 I005 I006 not found

**Comment by hgoerner** [comment]
fixed.
When sections are multiselected they will be added to movements. If section is already part of movement the user recieves a message.
