### ISSUE TITLE
Keyerror after loading after loading the ottrk data (after question window); already loaded a video/tracks befor but removed them to count another video

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTAnalytics#82]
successful
new Queue initiated
raspberrypi_FR20_2020-02-20_13-45-00.mp4
forward thread alive
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\gui.py", line 119, in load_video_and_add_frame
    view.image_alteration.manipulate_image()
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\image_alteration.py", line 38, in manipulate_image
    np_image = draw_tracks(
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\image_alteration.py", line 187, in draw_tracks
    df = tracks.loc[selectionlist]
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\venv\lib\site-packages\pandas\core\indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\venv\lib\site-packages\pandas\core\indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\venv\lib\site-packages\pandas\core\indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\venv\lib\site-packages\pandas\core\indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\venv\lib\site-packages\pandas\core\indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['62', '85', '158', '240', '250', '284', '363', '366', '380', '449', '562', '580', '583', '594', '598', '625', '758', '764', '1161', '1223', '1240', '1257', '1294', '1365', '1389', '1465', '1481', '1533', '1541', '1550', '1562', '1691', '1762', '1846', '1872', '1888', '1933', '1978', '2340'] not in index"

**Comment by hgoerner** [comment]
loading and deloading trackfile doestn lead to error anymore
