### ISSUE TITLE
Key Error in first frame after pressing "Show Bboxes" (Tracks and video loaded)

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTAnalytics#83]
Used video and ottrk:
[kleine Videodatei.zip](https://github.com/OpenTrafficCam/OTAnalytics/files/9300114/kleine.Videodatei.zip)

Error:
Traceback (most recent call last):
  File "C:\Users\Kollascheck\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\canvas.py", line 116, in <lambda>
    command=lambda event: self.slider_scroll(int(event)),
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\canvas.py", line 164, in slider_scroll
    view.image_alteration.manipulate_image(np_image=np_image)
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\image_alteration.py", line 44, in manipulate_image
    np_image = draw_bounding_box(
  File "C:\Users\Kollascheck\Desktop\VSC_workspace\OTC\OTAnalytics\OTAnalytics\view\image_alteration.py", line 226, in draw_bounding_box
    for detection in raw_detections[frame]:
KeyError: '0'

**Comment by hgoerner** [comment]
Error eliminated sind dataformat update. (iloc dataframe instead of iterating through keys)
